name: GitHub Actions 실행 # workflow 의 이름

on:
  push:
    branches:
      - main # main 브랜치에 push 될 때 아래의 workflow 를 실행

jobs:
  My-Deploy-job: # GitHub Actions 에서 실행될 Job 이름
    runs-on: ubuntu-latest # Actions 실행 환경
    steps: # Job 이 실행될 단계 정의
      - name: skhuring project client release
        uses: appleboy/ssh-action@master # Actions 의 appleboy/ssh-action 을 사용하여 SSH 접속 수행
        env: # 환경변수 설정
          FRONT_ENV_PROD: ${{ secrets.FRONT_ENV_PROD }} # 프론트엔드 환경변수 설정
        with:
          host: ${{ secrets.EC2_HOST }} # EC2 인스턴스의 공인 IP 주소 또는 도메인
          username: ${{ secrets.EC2_USERNAME }} # EC2에 접속할 사용자 이름
          key: ${{ secrets.EC2_PRIVATE_KEY }} # SSH 접속을 위한 비밀키
          envs: FRONT_ENV_PROD # 환경변수를 EC2 서버에 전달
          script_stop: true # 스크립트 실행 중 오류가 발생하면 즉시 종료
          script: |
            cd /home/ubuntu/skhuring-frontend
            git pull origin main
            echo "$FRONT_ENV_PROD" > .env.production
            sudo npm install
            sudo npm run build
            sudo systemctl restart nginx
